#include "bpf_gen.h"
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <unistd.h>
#include <iostream>
#include <fstream>
#include <sstream>

std::string generate_bpf_source(const Config &cfg, const std::string &out_c)
{
    std::ofstream f(out_c);
    if (!f) {
        std::cerr << "error: cannot write " << out_c << "\n";
        exit(1);
    }

    // 检查是否有 probe 需要 key 提取
    bool need_key = false;
    for (auto &p : cfg.probes)
        if (!p.key.empty()) need_key = true;

    // 是否需要 PT_REGS_PARM
    bool need_tracing_h = false;
    for (auto &p : cfg.probes)
        if (p.key == "arg1" || p.key == "arg2")
            need_tracing_h = true;

    f << "// Auto-generated by LensX V2 — do not edit\n";
    f << "#include \"vmlinux.h\"\n";
    f << "#include <bpf_helpers.h>\n";
    if (need_tracing_h)
        f << "#include <bpf_tracing.h>\n";

    f << "\nstruct event {\n";
    f << "    __u64 ts;\n";
    f << "    __u32 tid;\n";
    f << "    __u8  stage;\n";
    f << "    __u8  pad[3];\n";
    f << "    __u64 key;\n";     // always include key field
    f << "};\n\n";

    f << "struct {\n";
    f << "    __uint(type, BPF_MAP_TYPE_RINGBUF);\n";
    f << "    __uint(max_entries, 1 << 20);\n";
    f << "} rb SEC(\".maps\");\n\n";
    f << "char _license[] SEC(\"license\") = \"GPL\";\n\n";;

    for (auto &p : cfg.probes) {
        if (p.type == "tracepoint") {
            f << "SEC(\"tracepoint/" << p.event << "\")\n";
            // 需要读 ctx 字段时用具体类型，否则用 void 避免不完整类型错误
            if (p.key.substr(0, 5) == "ctx->") {
                // 从 event 名称提取 struct 类型名: "io_uring/io_uring_complete" → "trace_event_raw_io_uring_complete"
                std::string tp_name = p.event;
                auto slash = tp_name.rfind('/');
                if (slash != std::string::npos)
                    tp_name = tp_name.substr(slash + 1);
                f << "int tp_" << p.name << "(struct trace_event_raw_" << tp_name << " *ctx) {\n";
            } else {
                f << "int tp_" << p.name << "(void *ctx) {\n";
            }
        } else if (p.type == "kprobe" || p.type == "kretprobe") {
            f << "SEC(\"" << p.type << "/" << p.symbol << "\")\n";
            f << "int kp_" << p.name << "(struct pt_regs *ctx) {\n";
        } else {
            // uprobe — 符号名只在 attach 时需要，SEC 统一用 "uprobe"
            f << "SEC(\"uprobe\")\n";
            f << "int up_" << p.name << "(struct pt_regs *ctx) {\n";
        }

        f << "    struct event e = {};\n";
        f << "    e.ts    = bpf_ktime_get_ns();\n";
        f << "    e.tid   = (__u32)bpf_get_current_pid_tgid();\n";
        f << "    e.stage = " << p.stage << ";\n";
        // key 提取
        if (p.key == "arg1") {
            f << "    e.key   = PT_REGS_PARM1(ctx);\n";
        } else if (p.key == "arg2") {
            f << "    e.key   = PT_REGS_PARM2(ctx);\n";
        } else if (p.key.substr(0, 5) == "ctx->") {
            f << "    e.key   = " << p.key << ";\n";
        } else {
            f << "    e.key   = 0;\n";
        }
        f << "    bpf_ringbuf_output(&rb, &e, sizeof(e), 0);\n";
        f << "    return 0;\n";
        f << "}\n\n";
    }

    f.close();

    // 覆盖真实 vmlinux.h
    std::string vmlinux_src = "/home/qiwang/LensX/build/vmlinux.h";
    std::string vmlinux_dst = out_c.substr(0, out_c.rfind('/') + 1) + "vmlinux.h";
    if (access(vmlinux_src.c_str(), F_OK) == 0) {
        std::string cp = "cp -f " + vmlinux_src + " " + vmlinux_dst;
        system(cp.c_str());
    }

    return out_c;
}

std::string compile_bpf(const std::string &c_path)
{
    std::string base = c_path.substr(0, c_path.rfind('.'));
    std::string obj = base + ".bpf.o";
    std::string dir = base.substr(0, base.rfind('/') + 1);

    // 找 clang
    std::string clang = "clang";
    if (access("/usr/bin/clang", X_OK) == 0)
        clang = "/usr/bin/clang";

    std::string cmd = clang + " -g -O2 -target bpf -D__TARGET_ARCH_x86"
        + " -I" + dir
        + " -I/home/qiwang/LensX/libbpf/src"
        + " -I/home/qiwang/LensX/libbpf/include/uapi"
        + " -c " + c_path + " -o " + obj + " 2>/dev/null";

    int rc = system(cmd.c_str());
    if (rc != 0) {
        std::cerr << "error: BPF compilation failed (exit " << rc << ")\n";
        std::cerr << "  cmd: " << cmd << "\n";
        exit(1);
    }

    return obj;
}
